### ISSUE TITLE
Action slows down when the agent does

### ISSUE THREAD

**Issue by johnroper100** [johnroper100/CrowdMaster#9]
Someone had noticed in MASSIVE that when the agent slows down to not creash into somebody or something, it's animation slows down as well. Any ideas as to if this is dooable?

**Comment by Peter-Noble** [comment]
Yeah, this is something I've been thinking about for a while but the problem is that you can't keyframe the playback speed of NLA tracks (they can individually have different playback speeds but only one playback speed per action clip). A potential solution would be to extract the animation from the actions into a series of keyframes and then set the keyframes manually per frame. However, this would be loads of work so hasn't been done yet.

**Comment by johnroper100** [comment]
Yea, this was what the old BlenderPeople script did. Take a look in https://github.com/johnroper100/CrowdMaster/blob/master/old-bp-code/Locomotion.py

**Comment by Peter-Noble** [comment]
This is a bigger issue so I'll look into it when I have more time at the end of the week/next week.
